In [108]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
import string

## Dataset

There are 2 datasets. Fake news and Not fake news

In [109]:
data_fake = pd.read_csv('Dataset\Fake.csv')
data_true = pd.read_csv('Dataset\True.csv')

In [110]:
data_fake.head(2)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   

                date  
0  December 31, 2017  
1  December 31, 2017

In [111]:
data_true.head(2)

title  \
0  As U.S. budget fight looms, Republicans flip t...   
1  U.S. military to accept transgender recruits o...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   
1  WASHINGTON (Reuters) - Transgender people will...  politicsNews   

                 date  
0  December 31, 2017   
1  December 29, 2017

## Data Pre processing

Insert new column 'class' as the target feature

In [112]:
data_fake['class'] = 0
data_true['class'] = 1

In [113]:
data_fake.head(1)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   

                date  class  
0  December 31, 2017      0

In [114]:
data_true.head(1)

title  \
0  As U.S. budget fight looms, Republicans flip t...   

                                                text       subject  \
0  WASHINGTON (Reuters) - The head of a conservat...  politicsNews   

                 date  class  
0  December 31, 2017       1

In [115]:
data_fake.shape, data_true.shape

((23481, 5), (21417, 5))

In [116]:
data_fake.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23481 entries, 0 to 23480
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    23481 non-null  object
 1   text     23481 non-null  object
 2   subject  23481 non-null  object
 3   date     23481 non-null  object
 4   class    23481 non-null  int64 
dtypes: int64(1), object(4)
memory usage: 917.4+ KB


In [117]:
data_true.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21417 entries, 0 to 21416
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    21417 non-null  object
 1   text     21417 non-null  object
 2   subject  21417 non-null  object
 3   date     21417 non-null  object
 4   class    21417 non-null  int64 
dtypes: int64(1), object(4)
memory usage: 836.7+ KB


## Merge dataset

In [118]:
news_df = pd.concat([data_fake, data_true], axis = 0)   

#axis=0 or 'index' -> vertically
#axis=1 or 'column' -> horizontally
news_df.head(2)

title  \
0   Donald Trump Sends Out Embarrassing New Year’...   
1   Drunk Bragging Trump Staffer Started Russian ...   

                                                text subject  \
0  Donald Trump just couldn t wish all Americans ...    News   
1  House Intelligence Committee Chairman Devin Nu...    News   

                date  class  
0  December 31, 2017      0  
1  December 31, 2017      0

In [119]:
news_df.tail(2)

title  \
21415  Vatican upbeat on possibility of Pope Francis ...   
21416  Indonesia to buy $1.14 billion worth of Russia...   

                                                    text    subject  \
21415  MOSCOW (Reuters) - Vatican Secretary of State ...  worldnews   
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...  worldnews   

                   date  class  
21415  August 22, 2017       1  
21416  August 22, 2017       1

In [120]:
news_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44898 entries, 0 to 21416
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   title    44898 non-null  object
 1   text     44898 non-null  object
 2   subject  44898 non-null  object
 3   date     44898 non-null  object
 4   class    44898 non-null  int64 
dtypes: int64(1), object(4)
memory usage: 2.1+ MB


## Remove irrelavent columns

In [121]:
news_df = news_df.drop(['title', 'subject', 'date'], axis = 1)

In [122]:
# check null values
news_df.isnull().sum()

text     0
class    0
dtype: int64

In [123]:
news_df.head()

text  class
0  Donald Trump just couldn t wish all Americans ...      0
1  House Intelligence Committee Chairman Devin Nu...      0
2  On Friday, it was revealed that former Milwauk...      0
3  On Christmas day, Donald Trump announced that ...      0
4  Pope Francis used his annual Christmas Day mes...      0

In [124]:
# shuffle df
news_df = news_df.sample(frac=1, random_state=42)

# frac - fraction of rows to return when sampling
# random_state - reproductability 

In [125]:
news_df.head(3)

text  class
22216  21st Century Wire says Ben Stein, reputable pr...      0
4436   WASHINGTON (Reuters) - U.S. President Donald T...      1
1526   (Reuters) - Puerto Rico Governor Ricardo Rosse...      1

In [126]:
news_df.columns

Index(['text', 'class'], dtype='object')

In [127]:
# reset index
news_df.reset_index(inplace=True)

In [128]:
news_df.head(3)

index                                               text  class
0  22216  21st Century Wire says Ben Stein, reputable pr...      0
1   4436  WASHINGTON (Reuters) - U.S. President Donald T...      1
2   1526  (Reuters) - Puerto Rico Governor Ricardo Rosse...      1

In [129]:
# drop index column
news_df.drop(['index'], axis=1, inplace=True)

In [130]:
news_df.head(3)

text  class
0  21st Century Wire says Ben Stein, reputable pr...      0
1  WASHINGTON (Reuters) - U.S. President Donald T...      1
2  (Reuters) - Puerto Rico Governor Ricardo Rosse...      1

## Text preprocessing

text = text.lower(): This line converts all text to lowercase, which can be beneficial for standardizing the text data.

text = re.sub(r'\[.*?\]', '', text): This line uses a regular expression (re.sub) to remove text within square brackets ([...]) and the brackets themselves. The .*? pattern matches any characters (except newline) inside the square brackets in a non-greedy way.

text = re.sub(r'https?://\S+|www\.\S+', '', text): This line uses a regular expression to remove URLs starting with http:// or https:// and URLs starting with www.. \S+ matches one or more non-whitespace characters.

text = re.sub(r'<.*?>+', '', text): This line uses a regular expression to remove HTML tags. <.*?>+ matches any HTML tags (including their attributes) and removes them.

text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text): This line uses a regular expression to remove punctuation marks. string.punctuation contains a string of all punctuation characters. re.escape is used to escape these characters in the regular expression pattern.

text = re.sub(r'\n', '', text): This line removes newline characters (\n) from the text.

text = re.sub(r'\w*\d\w*', '', text): This line uses a regular expression to remove words containing digits. \w*\d\w* matches words that contain at least one digit.

In [131]:
def clean_text(text):
    text = text.lower()  # Convert text to lowercase
    text = re.sub(r'\[.*?\]', '', text)  # Remove text within square brackets and the brackets themselves
    text = re.sub(r'https?://\S+|www\.\S+', '', text)  # Remove URLs starting with http/https or www
    text = re.sub(r'<.*?>+', '', text)  # Remove HTML tags
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text)  # Remove punctuation marks
    text = re.sub(r'\n', '', text)  # Remove newline characters
    text = re.sub(r'\w*\d\w*', '', text)  # Remove words containing digits
    return text

In [132]:
# apply function to the dataset 
news_df['text'] = news_df['text'].apply(clean_text)

## Vectorize text data 

Vectorizing text data refers to the process of converting textual information into numerical vectors that machine learning algorithms can understand and process

X - input data, features or independent variables
y - output data, target variable, response variable, or dependent variable 

In [133]:
X = news_df['text']
y = news_df['class']

perform TF-IDF vectorization

In [134]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(X)

## Model building

Split dataset into Train and Test

In [137]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, y, test_size=0.25, random_state=42)

print("Training data shape:", X_train.shape, y_train.shape)
print("Testing data shape:", X_test.shape, y_test.shape)

Training data shape: (33673, 199463) (33673,)
Testing data shape: (11225, 199463) (11225,)


### Logistic regression

In [138]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(random_state=42)
lr.fit(X_train, y_train)

LogisticRegression(random_state=42)

In [151]:
import joblib
# Save the trained Logistic Regression model to a file
joblib.dump(lr, 'logistic_regression_model.pkl')

['logistic_regression_model.pkl']

In [139]:
# Make predictions on the testing data
y_pred = lr.predict(X_test)

In [140]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.9829844097995546
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.98      0.98      5863
           1       0.98      0.99      0.98      5362

    accuracy                           0.98     11225
   macro avg       0.98      0.98      0.98     11225
weighted avg       0.98      0.98      0.98     11225

Confusion Matrix:
[[5748  115]
 [  76 5286]]


### Random Forest Classifier

In [142]:
from sklearn.ensemble import RandomForestClassifier

rf_classifier = RandomForestClassifier(random_state=42)
rf_classifier.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [152]:
# Save the trained Random Forest model to a file
joblib.dump(rf_classifier, 'random_forest_model.pkl')

['random_forest_model.pkl']

In [143]:
# Make predictions on the testing data
y_pred_rf = rf_classifier.predict(X_test)

In [144]:
# Evaluate the classifier's performance
accuracy_rf = accuracy_score(y_test, y_pred_rf)
print("Random Forest Classifier Accuracy:", accuracy_rf)

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred_rf))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

Random Forest Classifier Accuracy: 0.9867260579064588
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5863
           1       0.99      0.99      0.99      5362

    accuracy                           0.99     11225
   macro avg       0.99      0.99      0.99     11225
weighted avg       0.99      0.99      0.99     11225

Confusion Matrix:
[[5786   77]
 [  72 5290]]


### Gradient Boosting Classifier

In [145]:
from sklearn.ensemble import GradientBoostingClassifier

gb_classifier = GradientBoostingClassifier(random_state=42)
gb_classifier.fit(X_train, y_train)

GradientBoostingClassifier(random_state=42)

In [153]:
# Save the trained Gradient Boosting model to a file
joblib.dump(gb_classifier, 'gradient_boosting_model.pkl')

['gradient_boosting_model.pkl']

In [146]:
# Make predictions on the testing data
y_pred_gb = gb_classifier.predict(X_test)

In [147]:
# Evaluate the classifier's performance
accuracy_gb = accuracy_score(y_test, y_pred_gb)
print("Gradient Boosting Classifier Accuracy:", accuracy_gb)

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred_gb))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_gb))

Gradient Boosting Classifier Accuracy: 0.995902004454343
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00      5863
           1       0.99      1.00      1.00      5362

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225

Confusion Matrix:
[[5831   32]
 [  14 5348]]


### Decision Tree Classifier

In [148]:
from sklearn.tree import DecisionTreeClassifier

dt_classifier = DecisionTreeClassifier(random_state=42)
dt_classifier.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [154]:
# Save the trained Decision Tree model to a file
joblib.dump(dt_classifier, 'decision_tree_model.pkl')

['decision_tree_model.pkl']

In [149]:
# Make predictions on the testing data
y_pred_dt = dt_classifier.predict(X_test)

In [150]:
# Evaluate the classifier's performance
accuracy_dt = accuracy_score(y_test, y_pred_dt)
print("Decision Tree Classifier Accuracy:", accuracy_dt)

# Print classification report (precision, recall, F1-score, support)
print("Classification Report:")
print(classification_report(y_test, y_pred_dt))

# Print confusion matrix
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Decision Tree Classifier Accuracy: 0.9961692650334075
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5863
           1       1.00      1.00      1.00      5362

    accuracy                           1.00     11225
   macro avg       1.00      1.00      1.00     11225
weighted avg       1.00      1.00      1.00     11225

Confusion Matrix:
[[5843   20]
 [  23 5339]]


## Model testing

In [ ]:
def output_lable(n):
    if n == 0:
        return "Fake News"
    elif n == 1:
        return "Not A Fake News"

def manual_testing(news):
    testing_news = {"text":[news]}
    new_def_test = pd.DataFrame(testing_news)
    new_def_test["text"] = new_def_test["text"].apply(clean_text)
    new_x_test = new_def_test["text"]
    new_xv_test = tfidf_vectorizer.transform(new_x_test)
    pred_LR = lr.predict(new_xv_test)
    pred_DT = dt_classifier.predict(new_xv_test)
    pred_GBC = gb_classifier.predict(new_xv_test)
    pred_RFC = rf_classifier.predict(new_xv_test)

    return print("\n\nLR Prediction: {) \nDT Prediction: {} \nGBC Prediction: {} \nRFC Prediction: {}".format(output_lable(pred_LR[0]),
                                                                                                              output_lable(pred_DT[0]),
                                                                                                              output_lable(pred_GBC[0]),
                                                                                                              output_lable(pred_RFC[0])))